version: '3'
services:
  frontend:
    build: ./frontend
    container_name: incluLex-frontend
    ports:
      - "5173:5173"
    networks:
      - incluLex-network  

  backend:
    build: ./backend
    container_name: incluLex-backend
    environment:
      PYTHONUNBUFFERED: 1    
    ports:
      - "3000:3000"
    networks:
      - incluLex-network   
    restart: on-failure  
    # volumes:
    #   - ./backend:/app/backend
    volumes:
      - ./frecuencia.db:/app/backend/frecuencia.db    
       

networks:
  incluLex-network:
    driver: bridge       