version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: incluLex-frontend
    ports:
      - "5173:5173"
    networks:
      - incluLex-network  

  backend:
    build: ./backend
    container_name: incluLex-backend
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "3000:3000"
    networks:
      - incluLex-network   
    restart: on-failure  
    volumes:
      - ./backend:/app/backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia       

networks:
  incluLex-network:
    driver: bridge
