version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend   
    ports:
      - "5173:5173"
    networks:
      - incluLex-network      

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - incluLex-network   
       

networks:
  incluLex-network:
    driver: bridge       